# Generated by Django 4.0.2 on 2022-06-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleScreen',
            new_name='TitleScreens',
        ),
    ]
