# Generated by Django 4.0.2 on 2022-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_rename_titlescreen_titlescreens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Napisz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('wykonanie', models.TextField(max_length=800)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sposoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaSposobu', models.CharField(max_length=255)),
                ('opisSposobu', models.TextField(max_length=800)),
            ],
        ),
    ]
