# Generated by Django 4.0.2 on 2022-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_napisz_sposoby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napisz',
            name='wykonanie',
            field=models.TextField(max_length=1200),
        ),
    ]
