# Generated by Django 4.0.2 on 2022-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_alter_napisz_wykonanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napisz',
            name='wykonanie',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='sposoby',
            name='opisSposobu',
            field=models.TextField(max_length=3000),
        ),
    ]
